<a href="https://colab.research.google.com/github/moribots/tensors/blob/main/transformer_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [1]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-02-08 06:25:49--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.06s   

2025-02-08 06:25:50 (18.1 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [2]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [4]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [5]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [6]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [7]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [8]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [9]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [10]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [11]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53

In [12]:
print(xb) # our input to the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [13]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [14]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [15]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.587916374206543


In [16]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


xiKi-RJ:CgqVuUa!U?qMH.uk!sCuMXvv!CJFfx;LgRyJknOEti.?I&-gPlLyulId?XlaInQ'q,lT$
3Q&sGlvHQ?mqSq-eON
x?SP fUAfCAuCX:bOlgiRQWN:Mphaw
tRLKuYXEaAXxrcq-gCUzeh3w!AcyaylgYWjmJM?Uzw:inaY,:C&OECW:vmGGJAn3onAuMgia!ms$Vb q-gCOcPcUhOnxJGUGSPJWT:.?ujmJFoiNL&A'DxY,prZ?qdT;hoo'dHooXXlxf'WkHK&u3Q?rqUi.kz;?Yx?C&u3Qbfzxlyh'Vl:zyxjKXgC?
lv'QKFiBeviNxO'm!Upm$srm&TqViqiBD3HBP!juEOpmZJyF$Fwfy!PlvWPFC
&WDdP!Ko,px
x
tREOE;AJ.BeXkylOVD3KHp$e?nD,.SFbWWI'ubcL!q-tU;aXmJ&uGXHxJXI&Z!gHRpajj;l.
pTErIBjx;JKIgoCnLGXrJSP!AU-AcbczR?


## The mathematical trick in self-attention

In [17]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [18]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [19]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [20]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [21]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [22]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [23]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [24]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [25]:
k.var()

tensor(1.0449)

In [26]:
q.var()

tensor(1.0700)

In [27]:
wei.var()

tensor(1.0918)

In [28]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [29]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [30]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [31]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [32]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [33]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [ ]:
import numpy as np

def analyze_einsum(equation, *tensors):
    """
    Analyze an einsum operation and deduce what kind of operation was performed.

    Parameters:
        equation (str): The einsum equation.
        *tensors: The input tensors.

    Returns:
        None: Prints the analysis.
    """
    # Get input shapes
    input_shapes = [tensor.shape for tensor in tensors]

    # Compute einsum output
    output = np.einsum(equation, *tensors)
    output_shape = output.shape

    # Extract equation components
    input_vars, output_vars = equation.split("->")
    input_vars = input_vars.split(",")

    # Identify contraction (summed over indices)
    all_indices = set("".join(input_vars))
    remaining_indices = set(output_vars)
    contracted_indices = all_indices - remaining_indices

    # Operation type deduction
    if len(contracted_indices) > 0:
        # Contraction (summation) is involved
        if len(input_vars) == 2:
            if len(contracted_indices) == 1:
                if len(output_vars) == 0:
                    operation_type = "Dot product"
                else:
                    operation_type = "Matrix multiplication"
            elif len(contracted_indices) == len(input_vars[0]):
                operation_type = "Tensor contraction (Full reduction)"
            else:
                operation_type = "Tensor contraction (Partial reduction)"
            contraction_details = f"Summed over indices: {contracted_indices}"
        else:
            operation_type = "Tensor contraction (Multiple tensors)"
            contraction_details = f"Summed over indices: {contracted_indices}"
    else:
        # No contraction, likely element-wise operation or broadcasting
        if len(input_vars) == 1:
            if len(output_vars) == len(input_vars[0]):
                operation_type = "Transposition or Reshaping"
                contraction_details = f"Rearranging dimensions from {input_shapes[0]} to {output_shape}"
            else:
                operation_type = "Diagonal Extraction or Reduction"
                contraction_details = "Extracting diagonal elements or reducing dimensions."
        elif len(input_vars) == 2:
            if input_shapes[0] == input_shapes[1]:
                operation_type = "Element-wise operation (e.g., addition, subtraction)"
                contraction_details = f"Element-wise operation between tensors with shapes {input_shapes}"
            else:
                operation_type = "Broadcasting"
                contraction_details = f"Broadcasting operation between tensors with shapes {input_shapes}"
        else:
            operation_type = "Element-wise or Broadcasting (Multiple Tensors)"
            contraction_details = "Complex element-wise or broadcasting operation between multiple tensors."

    # Print analysis
    print("=== Einsum Analysis ===")
    print(f"Equation: {equation}")
    print(f"Input Shapes: {input_shapes}")
    print(f"Output Shape: {output_shape}")
    print(f"Operation Type: {operation_type}")
    print(contraction_details)

def test_analyze_einsum():
    """Test cases for analyze_einsum function."""

    # Test cases for different operation types
    test_cases = [
        ("ij,jk->ik", (np.random.rand(3, 4), np.random.rand(4, 2)), "Matrix multiplication"),
        ("ij,ij->", (np.random.rand(3, 2), np.random.rand(3, 2)), "Dot product"),
        ("ijk,ijk->", (np.random.rand(2, 3, 4), np.random.rand(2, 3, 4)), "Tensor contraction (Full reduction)"),
        ("ijk,jkm->im", (np.random.rand(2, 3, 4), np.random.rand(3, 4, 5)), "Tensor contraction (Partial reduction)"),
        ("ij,jk,kl->il", (np.random.rand(2, 3), np.random.rand(3, 4), np.random.rand(4, 5)), "Tensor contraction (Multiple tensors)"),
        ("ij,ij->ij", (np.random.rand(3, 4), np.random.rand(3, 4)), "Hadamard product"),
        ("ij->ji", (np.random.rand(3, 4),), "Transposition or Reshaping"),
        ("ii->i", (np.random.rand(4, 4),), "Diagonal Extraction or Reduction"),
        ("ij,ij->ij", (np.random.rand(3, 4), np.random.rand(3, 4)), "Element-wise operation (e.g., addition, subtraction)"),
        ("ij,j->ij", (np.random.rand(3, 4), np.random.rand(4)), "Broadcasting"),
        ("ij,jk,k->ik", (np.random.rand(3, 4), np.random.rand(4, 2), np.random.rand(2)), "Matrix multiplication or tensor contraction")
    ]

    for equation, tensors, expected_type in test_cases:
        print("\n\n=== Test Case ===")
        print(f"Equation: {equation}")
        print(f"Expected Operation Type: {expected_type}\n")
        analyze_einsum(equation, *tensors)

# Run the test cases
test_analyze_einsum()


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
from einops import rearrange

# hyperparameters - these control various aspects of the model and training process
batch_size = 16 # how many independent sequences will we process in parallel?  Higher values mean more data processed at once.
block_size = 32 # what is the maximum context length for predictions?  How many previous characters the model considers.
max_iters = 5000 # how many training iterations to run. More iterations can lead to better performance, but also overfitting.
eval_interval = 100 # how often to evaluate the model's performance on the validation set.
learning_rate = 1e-3 # the learning rate for the optimizer.  Controls how quickly the model learns.
device = 'cuda' if torch.cuda.is_available() else 'cpu' # use GPU if available, otherwise use CPU.
eval_iters = 200 # number of iterations to use when evaluating the loss.
n_embd = 64 # number of dimensions in the character embeddings.  Higher values mean more complex representations.
n_head = 4 # number of attention heads in the multi-head attention mechanism.
n_layer = 4 # number of layers in the Transformer block.  More layers can capture more complex patterns.
dropout = 0.0 # dropout rate for regularization.  Helps prevent overfitting.
# ------------

torch.manual_seed(1337) # set a random seed for reproducibility.

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f: # open the input text file.
    text = f.read() # read the entire file into a string.

# here are all the unique characters that occur in this text
chars = sorted(list(set(text))) # create a sorted list of unique characters in the text.
vocab_size = len(chars) # the size of the vocabulary (number of unique characters).
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) } # string to integer mapping.
itos = { i:ch for i,ch in enumerate(chars) } # integer to string mapping.
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers.
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string.

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long) # encode the text and convert it to a tensor.
n = int(0.9*len(data)) # first 90% will be train, rest val.
train_data = data[:n] # training data.
val_data = data[n:] # validation data.

# data loading - provides batches of data to the model during training
def get_batch(split):
    """
    Generates a small batch of data of inputs x and targets y.

    This function takes a data split ('train' or 'val') and returns a batch of input sequences (x) and their corresponding target sequences (y).
    The input sequences are chunks of text, and the target sequences are the same chunks shifted forward by one character.  This is how the model learns to predict the next character.
    The function randomly selects starting positions within the data and stacks the resulting sequences into tensors.

    Args:
        split: The data split to use ('train' or 'val').

    Returns:
        A tuple containing the input tensor x and the target tensor y.
    """
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data # select the appropriate data split.
    ix = torch.randint(len(data) - block_size, (batch_size,)) # generate random starting indices for the sequences.
    x = torch.stack([data[i:i+block_size] for i in ix]) # create the input sequences.
    y = torch.stack([data[i+1:i+block_size+1] for i in ix]) # create the target sequences (shifted by one).
    x, y = x.to(device), y.to(device) # move the data to the device (GPU if available).
    return x, y

@torch.no_grad() # decorator to disable gradient calculation during evaluation.
def estimate_loss():
    """
    Estimates the loss on the training and validation sets.

    This function evaluates the model's performance on both the training and validation sets.  It calculates the average loss over a number of iterations.
    By comparing the training loss and validation loss, we can get an idea of how well the model is generalizing to unseen data.

    Returns:
        A dictionary containing the mean loss for the training and validation sets.
    """
    out = {} # dictionary to store the losses for each split.
    model.eval() # set the model to evaluation mode.
    for split in ['train', 'val']: # loop over the training and validation splits.
        losses = torch.zeros(eval_iters) # tensor to store the losses for each iteration.
        for k in range(eval_iters): # loop over the evaluation iterations.
            X, Y = get_batch(split) # get a batch of data.
            logits, loss = model(X, Y) # get the logits and loss from the model.
            losses[k] = loss.item() # store the loss.
        out[split] = losses.mean() # calculate the mean loss.
    model.train() # set the model back to training mode.
    return out

class Head(nn.Module):
    """
    One head of self-attention.

    This module is the core building block of the attention mechanism. It takes input sequences and learns to focus on different parts of the sequence when making predictions.
    It does this by calculating "attention weights" which determine how much influence each element in the sequence has on the output.

    Specifically, it calculates three things:
    - Key: Represents the information to be retrieved.
    - Query: Represents what we are looking for.
    - Value: Represents the information to be aggregated.

    It then calculates attention scores by comparing the Query and Key. These scores are used to weight the Value, producing the output.

    Here's a simplified visualization:

    ```
    Input (x):  [A] [B] [C] [D]
                 |   |   |   |
                 v   v   v   v
    Key (k):    [k_A] [k_B] [k_C] [k_D]
    Query (q):  [q_A] [q_B] [q_C] [q_D]
    Value (v):  [v_A] [v_B] [v_C] [v_D]

    Attention Weights:
         A   B   C   D
      A [w_AA w_AB w_AC w_AD]
      B [w_BA w_BB w_BC w_BD]
      C [w_CA w_CB w_CC w_CD]
      D [w_DA w_DB w_DC w_DD]

    Output: Weighted sum of Values based on Attention Weights.
    ```
    """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False) # linear layer for the key.
        self.query = nn.Linear(n_embd, head_size, bias=False) # linear layer for the query.
        self.value = nn.Linear(n_embd, head_size, bias=False) # linear layer for the value.
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size))) # lower triangular mask for causal attention.

        self.dropout = nn.Dropout(dropout) # dropout layer.

    def forward(self, x):
        B, T, C = x.shape # batch size, sequence length, embedding_dimension.
        k = self.key(x)   # (B,T,C) - calculate the keys.
        q = self.query(x) # (B,T,C) - calculate the queries.

        # compute attention scores ("affinities") using einops
        # (B, T, C) @ (B, C, T) -> (B, T, T)
        # b: batch size, c: embedding dimension, i: query sequence length dimension (T), j: key sequence length dimension (T)
        """
        Use Einstein Summation (einsum), which lets me perform:
          - Summation: Summing over specified dimensions of a tensor.
          - Contraction: Performing dot products, matrix multiplications, and other contractions between tensors.
          - Transposition: Rearranging the dimensions of a tensor.
          - Broadcasting: Applying operations to tensors with different shapes.

        You just tell it the input and output dimensions, and it figures out the appropriate operation.
        """
        wei = torch.einsum('b i c, b j c -> b i j', q, k)
        wei = wei * (k.shape[-1]**-0.5)  # Scaling by embedding_dimension**-0.5
        # Apply the lower triangular max for cheap
        wei = wei.masked_fill(self.tril[:T,:T] == 0, float('-inf'))  # (B, T, T)
        # Normalize the attention weights.
        wei = F.softmax(wei, dim=-1)  # (B, T, T)
        # Apply the dropout
        wei = self.dropout(wei)

        # Compute the values.
        v = self.value(x)  # (B, T, C)
        # perform the weighted aggregation of the values using einops
        # b: batch size, c: embedding dimension, i: query sequence length dimension (T), j: key sequence length dimension (T)
        out = torch.einsum('b i j, b j h -> b i h', wei, v)  # Assuming v has shape (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """
    Multiple heads of self-attention in parallel.

    This module extends the single attention head by creating multiple heads.  Each head learns to focus on different aspects of the input sequence, allowing the model to capture more complex relationships.
    The outputs of all heads are then concatenated and projected to the original embedding dimension.

    Imagine each head as looking at the input from a slightly different angle:

    ```
    Input (x):  [A] [B] [C] [D]

    Head 1:     [Attention_1(A)] [Attention_1(B)] [Attention_1(C)] [Attention_1(D)]
    Head 2:     [Attention_2(A)] [Attention_2(B)] [Attention_2(C)] [Attention_2(D)]
    ...
    Head N:     [Attention_N(A)] [Attention_N(B)] [Attention_N(C)] [Attention_N(D)]

    Concatenated: [Attention_1(A), Attention_2(A), ..., Attention_N(A)] ...

    Projected: Back to the original embedding dimension.
    ```
    """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)]) # create multiple attention heads.
        self.proj = nn.Linear(n_embd, n_embd) # linear layer to project the concatenated heads.
        self.dropout = nn.Dropout(dropout) # dropout layer.

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1) # concatenate the outputs of the heads.
        out = self.dropout(self.proj(out)) # apply dropout and projection.
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential( # a sequential network.
            nn.Linear(n_embd, 4 * n_embd), # linear layer.
            nn.ReLU(), # ReLU activation function.
            nn.Linear(4 * n_embd, n_embd), # linear layer.
            nn.Dropout(dropout), # dropout layer.
        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head # calculate the size of each attention head.
        self.sa = MultiHeadAttention(n_head, head_size) # multi-head self-attention.
        self.ffwd = FeedFoward(n_embd) # feed-forward network.
        self.ln1 = nn.LayerNorm(n_embd) # layer normalization.
        self.ln2 = nn.LayerNorm(n_embd) # layer

    def forward(self, x):
        x = x + self.sa(self.ln1(x)) # Apply self-attention and add to the input.
        x = x + self.ffwd(self.ln2(x)) # Apply feed-forward network and add to the result.
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.209729 M parameters
step 0: train loss 4.4109, val loss 4.4016
step 100: train loss 2.6510, val loss 2.6603
step 200: train loss 2.4942, val loss 2.4904
step 300: train loss 2.3903, val loss 2.4020
step 400: train loss 2.3213, val loss 2.3282
step 500: train loss 2.2540, val loss 2.2709
step 600: train loss 2.1951, val loss 2.2051
step 700: train loss 2.1669, val loss 2.1894
step 800: train loss 2.1247, val loss 2.1523
step 900: train loss 2.0768, val loss 2.1109
step 1000: train loss 2.0558, val loss 2.0895
step 1100: train loss 2.0280, val loss 2.0826
step 1200: train loss 1.9985, val loss 2.0474
step 1300: train loss 1.9886, val loss 2.0349
step 1400: train loss 1.9532, val loss 2.0056
step 1500: train loss 1.9358, val loss 1.9998
step 1600: train loss 1.9231, val loss 2.0098
step 1700: train loss 1.9110, val loss 1.9890
step 1800: train loss 1.8801, val loss 1.9719
step 1900: train loss 1.8768, val loss 1.9610
step 2000: train loss 1.8535, val loss 1.9699
step 2100: train loss 1.